apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::893895740383:role/profanity-cluster-worker-nodes-NodeInstanceRole-1DKMLYZE3NA48
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
      - userarn: arn:aws:iam::893895740383:user/anathan
        username: anathan
        groups:
          - system:masters
