apiVersion: "config.istio.io/v1alpha2"
kind: denier
metadata:
  name: denyhandler
spec:
  status:
    code: 403
    message: Not allowed
---
apiVersion: "config.istio.io/v1alpha2"
kind: checknothing
metadata:
  name: denyrequest
spec:
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: denyrule
spec:
  match: request.path.startsWith("/another") && request.headers["appkey"] == "anotherkey"
  actions:
  - handler: denyhandler.denier
    instances: [ denyrequest.checknothing ]
